name: p1_donut_app_geisler_quintal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.4.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - lib/Images_PanCakes/
  - lib/Images_Burger/
  - lib/images_s/
  - lib/Images_Pizza/
  - lib/images/
  - lib/icons/